name       : firewalld
version    : 0.4.4.6
release    : 5
source     :
    - https://github.com/firewalld/firewalld/archive/v0.4.4.6.tar.gz : a7bf9dd341f3f4c261fa8a8e217160ec815e9dbf32edc25aed44719a2273e94e
license    : GPL-2.0
component  : security
summary    :
    - Firewall daemon with D-Bus interface
    - applet : The firewall Qt panel applet provides a status information of firewalld and also the firewalld settings
description: |
    firewalld provides a dynamically managed firewall with support for network or 
    firewall zones to define the trust level of network connections or interfaces. 
    It has support for IPv4, IPv6 firewall settings and for ethernet bridges and a 
    separation of runtime and permanent configuration options. It also provides an 
    interface for services or applications to add ip*tables and ebtables rules 
    directly.
patterns   :
    - applet :
        - /etc/firewall/applet.conf
        - /etc/xdg/autostart/firewall-applet.desktop
        - /usr/bin/firewall-applet
        - /usr/share/icons/hicolor/*/apps/*applet*.*
        - /usr/share/icons/hicolor/scalable/apps/*applet*.*
        - /usr/share/man/man1/firewall-applet.1
builddeps  :
    - pkgconfig(libipset)
    - docbook-xml
    - ebtables
    - iptables
rundeps    :
    - ebtables
    - iptables
    - ipset
    - python-slip
    - applet :
        - firewalld
        - python-qt5
setup      : |
    %autogen --enable-systemd \
             --disable-rpmmacros
build      : |
    %make
install    : |
    %make_install
