name       : firewalld
version    : 1.3.2
release    : 13
source     :
    - https://github.com/firewalld/firewalld/archive/refs/tags/v1.3.2.tar.gz : 3be5a3caa36d1026c5b72d3f61dd963dccd953791b04af03d9946b24bef8391e
license    : GPL-2.0-or-later
component  :
    - security
    - applet : security
    - config : security
homepage   : https://firewalld.org/
summary    :
    - Firewall daemon with D-Bus interface
    - applet : The firewall Qt panel applet provides a status information of firewalld and also the firewalld settings
    - config : Application to configure firewalld
description: |
    firewalld provides a dynamically managed firewall with support for network or firewall zones to define the trust level of network connections or interfaces. It has support for IPv4, IPv6 firewall settings and for ethernet bridges and a separation of runtime and permanent configuration options. It also provides an interface for services or applications to add ip*tables and ebtables rules directly.
patterns   :
    - applet :
        - /usr/bin/firewall-applet
        - /etc/firewall/applet.conf
        - /etc/xdg/autostart/firewall-applet.desktop
        - /usr/share/icons/hicolor/*/apps/*applet*.*
        - /usr/share/icons/hicolor/scalable/apps/*applet*.*
        - /usr/share/man/man1/firewall-applet.1
    - config :
        - /usr/bin/firewall-config
        - /usr/share/firewalld/firewall-config.glade
        - /usr/share/firewalld/gtk3_chooserbutton.py*
        - /usr/share/firewalld/gtk3_niceexpander.py*
        - /usr/share/applications/firewall-config.desktop
        - /usr/share/metainfo/firewall-config.appdata.xml
        - /usr/share/icons/hicolor/*/apps/firewall-config*.*
        - /usr/man/man1/firewall-config*.1*
builddeps  :
    - pkgconfig(libipset)
    - pkgconfig(libnftnl)
    - pkgconfig(pygobject-3.0)
    - gettext-devel
    - docbook-xml
    - nftables
    - podman
rundeps    :
    - ipset
    - nftables
    - python3-dbus
    - python-capng
    - python-gobject
    - applet :
        - firewalld-config
        - python3-qt5
    - config :
        - firewalld
        - libgtk-3
setup      : |
    %autogen --disable-schemas-compile \
             --disable-sysconfig \
             PYTHON=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
