name       : firewalld
version    : 0.4.4.2
release    : 1
source     :
    - https://fedorahosted.org/released/firewalld/firewalld-0.4.4.2.tar.bz2 : 615dcd478d3b8459053811d08970e45e7f44942e2f93e57097e7ce0a5f27ba4a
license    : GPL-2.0
component  : security
summary    : Firewall daemon with D-Bus interface
description: |
    firewalld provides a dynamically managed firewall with support for network or 
    firewall zones to define the trust level of network connections or interfaces. 
    It has support for IPv4, IPv6 firewall settings and for ethernet bridges and a 
    separation of runtime and permanent configuration options. It also provides an 
    interface for services or applications to add ip*tables and ebtables rules 
    directly. 
builddeps  :
    - pkgconfig(libipset)
    - docbook-xml
    - ebtables
    - iptables
rundeps    :
    - ebtables
    - iptables
setup      : |
    %configure --enable-systemd \
               --disable-rpmmacros
build      : |
    %make
install    : |
    %make_install
