name       : firewalld
version    : 0.4.4.4
release    : 3
source     :
    - https://github.com/t-woerner/firewalld/archive/v0.4.4.4.tar.gz : 8726bb7c15c180191b81764072041bebd371664fcbc25a0eafffc35c707b3df9
license    : GPL-2.0
component  : security
summary    : Firewall daemon with D-Bus interface
description: |
    firewalld provides a dynamically managed firewall with support for network or 
    firewall zones to define the trust level of network connections or interfaces. 
    It has support for IPv4, IPv6 firewall settings and for ethernet bridges and a 
    separation of runtime and permanent configuration options. It also provides an 
    interface for services or applications to add ip*tables and ebtables rules 
    directly. 
builddeps  :
    - pkgconfig(libipset)
    - docbook-xml
    - ebtables
    - iptables
rundeps    :
    - ebtables
    - iptables
    - ipset
    - python-slip
setup      : |
    %autogen --enable-systemd \
             --disable-rpmmacros
build      : |
    %make
install    : |
    %make_install
